import Vue from 'vue';
import BaseSearchForm from './base-search-form';
import BaseInput from './base-input';
import BaseTable from './base-table';
import BaseForm from './base-form';
import BaseFormGroup from './base-form-group';
import BaseUploadAvatar from './base-upload-avatar';
import BaseAvatar from './base-avatar';
import BaseHr from './base-hr';
import BaseSelect from './base-select';
import BaseCharAvatar from './base-char-avatar.vue';

Vue.component('BaseSearchForm', BaseSearchForm);
Vue.component('BaseInput', BaseInput);
Vue.component('BaseTable', BaseTable);
Vue.component('BaseForm', BaseForm);
Vue.component('BaseFormGroup', BaseFormGroup);
Vue.component('BaseUploadAvatar', BaseUploadAvatar);
Vue.component('BaseAvatar', BaseAvatar);
Vue.component('BaseHr', BaseHr);
Vue.component('BaseSelect', BaseSelect);
Vue.component('BaseCharAvatar', BaseCharAvatar);
